language: r

sudo: false

cache: packages

warnings_are_errors: false

r_github_packages:
  - jimhester/covr
  - dkahle/ggmap

after_success:
  - Rscript -e 'library(covr); coveralls()'
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
